server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:meetings;MODE=Oracle
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: America/New_York

logging.level:
  org:
    springframework:
      jdbc:
        core:
          JdbcTemplate: DEBUG
          StatementCreatorUtils: TRACE

    hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE